AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation Template for EC2 instance with Nginx'

Resources:
  easypassSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07d9b9ddc6cd8dd30
      InstanceType: t2.micro
      KeyName: easypass-keypair
      SecurityGroupIds:
        - !Ref easypassSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          exec > >(tee /var/log/userdata.log|logger -t user-data -s 2>/dev/console) 2>&1
          echo "Starting UserData execution at $(date)"
          apt-get update -y
          apt-get install nginx -y
          systemctl start nginx
          systemctl enable nginx
          mkdir /var/easypass
          cd mkdir /var/easypass
          

Outputs:
  InstanceId:
    Description: Instance ID of the newly created EC2 instance
    Value: !Ref MyEC2Instance
    Export:
      Name: !Sub "${AWS::StackName}-InstanceId"